# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidge = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidge.setGeometry(QtCore.QRect(0, 0, 411, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidge.setFont(font)
        self.tabWidge.setObjectName("tabWidge")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 491, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_start = QtWidgets.QPushButton(self.frame_3)
        self.btn_start.setGeometry(QtCore.QRect(60, 60, 93, 28))
        self.btn_start.setObjectName("btn_start")
        self.frame_show_mouse = QtWidgets.QFrame(self.frame_3)
        self.frame_show_mouse.setGeometry(QtCore.QRect(280, 20, 50, 50))
        self.frame_show_mouse.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show_mouse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show_mouse.setObjectName("frame_show_mouse")
        self.txt_result = QtWidgets.QLabel(self.frame_3)
        self.txt_result.setGeometry(QtCore.QRect(40, 200, 110, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_result.setFont(font)
        self.txt_result.setObjectName("txt_result")
        self.txt_show_result = QtWidgets.QLabel(self.frame_3)
        self.txt_show_result.setGeometry(QtCore.QRect(130, 200, 201, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_show_result.setFont(font)
        self.txt_show_result.setObjectName("txt_show_result")
        self.btn_cancel = QtWidgets.QPushButton(self.frame_3)
        self.btn_cancel.setGeometry(QtCore.QRect(60, 100, 93, 28))
        self.btn_cancel.setObjectName("btn_cancel")
        self.frame_show_mouse_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_show_mouse_2.setGeometry(QtCore.QRect(270, 110, 80, 80))
        self.frame_show_mouse_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show_mouse_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show_mouse_2.setObjectName("frame_show_mouse_2")
        self.tabWidge.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(30, 50, 331, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_input_1 = QtWidgets.QPushButton(self.frame_2)
        self.btn_input_1.setGeometry(QtCore.QRect(30, 110, 93, 28))
        self.btn_input_1.setObjectName("btn_input_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 110, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_show_1 = QtWidgets.QFrame(self.frame_2)
        self.frame_show_1.setGeometry(QtCore.QRect(40, 30, 61, 51))
        self.frame_show_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show_1.setObjectName("frame_show_1")
        self.frame_show_2 = QtWidgets.QFrame(self.frame_2)
        self.frame_show_2.setGeometry(QtCore.QRect(180, 30, 61, 51))
        self.frame_show_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_show_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_show_2.setObjectName("frame_show_2")
        self.tabWidge.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidge.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "Bắt đầu"))
        self.txt_result.setText(_translate("MainWindow", "Kết quả:"))
        self.txt_show_result.setText(_translate("MainWindow", "TextLabel"))
        self.btn_cancel.setText(_translate("MainWindow", "Huỷ"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab), _translate("MainWindow", "Trang chủ"))
        self.btn_input_1.setText(_translate("MainWindow", "Nhập ảnh 1"))
        self.pushButton_3.setText(_translate("MainWindow", "Nhập ảnh 2"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_2), _translate("MainWindow", "Nhập ảnh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
